### ISSUE TITLE
建议增加分P上传和上传完成后删除录播文件的参数~~

### ISSUE THREAD

**Issue by Alexadnar** [valkjsaaa/auto-bilibili-recorder#12]
RT，建议增加分P上传，以满足不同观众的需求~~同时建议增加上传完毕后删除录播文件的选项，方便部署在服务器上~
PS：判断视频是否上传成功的逻辑好像有点问题，很多时候上传成功但是仍然会判断上传失败，导致机器人一直在不停地重试上传~

**Comment by valkjsaaa** [comment]
应该不难改，要不你交个 pull request？可以在直播间参数里加一个设置

**Comment by valkjsaaa** [comment]
上传至少修复了，先 close 了
