### ISSUE TITLE
请问有没有直接上传不搞压制弹幕的功能呀

### ISSUE THREAD

**Issue by xiaocainiao2020** [valkjsaaa/auto-bilibili-recorder#14]
想直接录好了上传原视频，不搞什么高能进度条也不压制弹幕上去，这个需要怎么弄呢？

**Comment by valkjsaaa** [comment]
我想了想，很难，因为有的时候主播换分辨率了（比如 pk），那没法生成 flv 文件啊，还是得从头到尾压一遍。跟压弹幕的开销差不多了啊。而且有的时候低开销生成的合并文件直接上传B站会报转码错误，完整压制一遍的几乎一定不会报错，不知道你想怎么处理呢？

**Comment by Heporis** [comment]
> 目前没办法，建议交个 pull request，加一个 configuration toggle

怎么换成录制斗鱼的呢

**Comment by Heporis** [comment]
> 我想了想，很难，因为有的时候主播换分辨率了（比如 pk），那没法生成 flv 文件啊，还是得从头到尾压一遍。跟压弹幕的开销差不多了啊。而且有的时候低开销生成的合并文件直接上传B站会报转码错误，完整压制一遍的几乎一定不会报错，不知道你想怎么处理呢？

你这个是重新编码压制做成硬字幕的吗？可不可以直接把ass字幕和视频封装在一起，做成软字幕，然后上传让B站自己编码？反正B站都要压制一遍，这样不用本地编码又快又省算力😏

**Comment by valkjsaaa** [comment]
> > 目前没办法，建议交个 pull request，加一个 configuration toggle
> 
> 怎么换成录制斗鱼的呢

没办法，自己魔改吧
