### ISSUE TITLE
请问有考虑移植arm版本的镜像吗？

### ISSUE THREAD

**Issue by notplus** [valkjsaaa/auto-bilibili-recorder#2]
请问有考虑移植arm版本的镜像吗？想在树莓派(arm 32)上部署，自己移植的时候出现比较多的问题，想问问是否有移植的计划。

**Comment by valkjsaaa** [comment]
我太懒了，你移植遇到什么问题了啊？应该用支持 arm 的 docker 然后在 clone 好的 repo 里
```
docker build --platform linux/arm/v7 --squash -t valkjsaaa/auto-bilibili-recorder:3.6 --build-arg COMMON_IMAGE=ubuntu:20.04 .
```
就行了吧？有什么特殊的吗？

**Comment by notplus** [comment]
构建的时候会提示架构不一致，主要是arm平台下dotnet在编译你修改过的[B站录播姬](https://github.com/Bililive/BililiveRecorder)会报错，所以我在尝试直接下载预编译好的二进制文件进行后续构建，感谢您的回复。
