### ISSUE TITLE
怎么运行镜像

### ISSUE THREAD

**Issue by ssssss1111** [valkjsaaa/auto-bilibili-recorder#20]
配置文件是用你的示例文件来修改嘛？ 然后怎么运行镜像？docker没有搭建镜像 要搭建吗？

**Comment by valkjsaaa** [comment]
对
看 “运行 docker 镜像：”那一块

**Comment by ssssss1111** [comment]
嗯 无GPU 要怎么用 复制去哪里才能运行docker 镜像 不懂

**Comment by valkjsaaa** [comment]
sudo docker run -d --restart=always --name auto-bilibili-recorder -v ${录制目标文件夹}:/storage ghcr.io/valkjsaaa/auto-bilibili-recorder:master

这个啊

**Comment by ssssss1111** [comment]
PS D:\auto-bilibili-recorder-master> PS D:\auto-bilibili-recorder-master> sudo docker run -d --restart=always --name auto-bilibili-recorder -v ${录制目标文件夹}:/storage ghcr.io/valkjsaaa/auto-bilibili-recorder:master
>> sudo : 无法将“sudo”项识别为 cmdlet、函数、脚本文件或可运行程序的名称。请检查名称的拼写，如果包括路径，请确保路径正 确
>> ，然后再试一次。
>> 所在位置 行:1 字符: 1
>> + sudo docker run -d --restart=always --name auto-bilibili-recorder -v  ...
>> + ~~~~
>>     + CategoryInfo          : ObjectNotFound: (sudo:String) [], CommandNotFoundException
>>     + FullyQualifiedErrorId : CommandNotFoundException
所在位置 行:5 字符: 2
+ + sudo docker run -d --restart=always --name auto-bilibili-recorder - ...
+  ~
一元运算符“+”后面缺少表达式。
所在位置 行:5 字符: 3
+ + sudo docker run -d --restart=always --name auto-bilibili-recorder - ...
+   ~~~~
表达式或语句中包含意外的标记“sudo”。
所在位置 行:6 字符: 2
+ + ~~~~
+  ~
一元运算符“+”后面缺少表达式。
所在位置 行:6 字符: 3
+ + ~~~~
+   ~~~~
表达式或语句中包含意外的标记“~~~~”。
所在位置 行:7 字符: 6
+     + CategoryInfo          : ObjectNotFound: (sudo:String) [], Comma ...
+      ~
一元运算符“+”后面缺少表达式。
所在位置 行:7 字符: 7
+     + CategoryInfo          : ObjectNotFound: (sudo:String) [], Comma ...
+       ~~~~~~~~~~~~
表达式或语句中包含意外的标记“CategoryInfo”。
所在位置 行:8 字符: 6
+     + FullyQualifiedErrorId : CommandNotFoundException
+      ~
一元运算符“+”后面缺少表达式。
所在位置 行:8 字符: 7
+     + FullyQualifiedErrorId : CommandNotFoundException
+       ~~~~~~~~~~~~~~~~~~~~~
表达式或语句中包含意外的标记“FullyQualifiedErrorId”。
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : MissingExpressionAfterOperator

PS D:\auto-bilibili-recorder-master>

**Comment by ssssss1111** [comment]
![20220420084918](https://user-images.githubusercontent.com/104035379/164125194-b11cae61-0564-4d45-a061-c5e6c3597de8.png)
抱歉还是不太懂emmm

**Comment by valkjsaaa** [comment]
sudo 去掉，${录制目标文件夹} 换成你放 yaml 配置文件的地方

**Comment by ssssss1111** [comment]
PS D:\auto-bilibili-recorder-master> docker run -d --restart=always --name auto-bilibili-recorder -v ${录制目标文件夹}:/storage ghcr.io/valkjsaaa/auto-bilibili-recorder:master
Unable to find image 'ghcr.io/valkjsaaa/auto-bilibili-recorder:master' locally
master: Pulling from valkjsaaa/auto-bilibili-recorder
08c01a0ec47e: Pull complete
6380f53532be: Pull complete
807f4ceb502d: Pull complete
18e4107b980d: Pull complete
7640b067e921: Pull complete
b087a0fcb874: Pull complete
af4e18c597be: Pull complete
6869fe93eb74: Pull complete
2fadae56f89c: Pull complete
31129e35c63b: Pull complete
c6e9ae5ea3dd: Pull complete
cacc96076cf9: Pull complete
ce214da22073: Pull complete
46c89e09e4dc: Downloading [==================================================>]  538.8MB/538.8MB
75563f77ab34: Download complete
d55cc68b1955: Download complete
b6efe9e91076: Download complete
9a6c5e1e5853: Download complete
031a6749f1d9: Download complete
8065ac4bd539: Download complete
d7fccd25be41: Download complete
a48a00537587: Download complete
c12f386dfae4: Download complete
d6fa7596f637: Download complete
9575c1b6c70f: Download complete
9d38a9b2d740: Download complete
92e4d118090c: Download complete
bb60b13504d7: Download complete
docker: unexpected EOF.
See 'docker run --help'.

**Comment by valkjsaaa** [comment]
网不好，重新跑
