### ISSUE TITLE
docker failed to start service utility VM 

### ISSUE THREAD

**Issue by neko886** [valkjsaaa/auto-bilibili-recorder#21]
作者您好，请教下关于docker显示无法启动VM的问题，docker版本信息和脚本logs，可见下图，麻烦您了。
我用的是腾讯云轻量应用服务器，系统是Windows Server 2019，因为是公有云所以不支持Hyper-V二次虚拟化。
（通宵搞了四五个晚上，从零开始琢磨，眼看最后一步就要成功了....结果5555）
![QQ截图20220420060230](https://user-images.githubusercontent.com/103251269/164109582-6f4f9e50-599d-4137-9cd1-6fd0cd6bbd4d.jpg)
![QQ截图20220420062502](https://user-images.githubusercontent.com/103251269/164111574-20d5e114-1e94-4f5b-bb51-0adbaca028fa.jpg)
![QQ截图20220419045649](https://user-images.githubusercontent.com/103251269/164109645-95f74e29-af71-49ca-85f1-c408b79d5933.jpg)

**Comment by valkjsaaa** [comment]
windows 上运行 docker 需要先开一个 linux 虚拟机才行。建议直接开一个 ubuntu 服务器，别用 windows server

**Comment by neko886** [comment]
感谢作者及时回复！我又经过数日琢磨，现已成功用上了弹幕高能版功能，很喜欢这个功能。
（好像有时候高能条不准，比如全场最高能，点最高能去看了左右都没有弹幕，会不会是把送红包礼物之类的弹幕也算进去了）

另外还有几个疑问想麻烦作者解答：
1.自动上传投稿的时候，我看到先投稿一次无弹幕版本，无弹幕版本审核完后，又投稿了一个弹幕高能版本覆盖了无弹幕版本。最后只剩下高能版本。这个两次投稿是属于正常运行吗

2.单独使用 Danmaku Tools 想分析下弹幕流水高能等，结果发现使用不了。不知道是py版本没切换对还是用户权限不对，亦或者XML文件不对。
![M 95E6E1~72GV9 ROU_X IM](https://user-images.githubusercontent.com/103251269/164950402-64125a0f-04a3-4e9d-8e22-4beccd02a0b1.png)

**Comment by valkjsaaa** [comment]
1. 自动换源是正常的行为，就是这么实现的。
2. 很可能你没装那个包，`danmaku_tools` 使用请见 https://github.com/valkjsaaa/danmaku_tools 。有问题去那边提 issue 吧。

**Comment by neko886** [comment]
> 1. 自动换源是正常的行为，就是这样实现的。
> 2. 很可能你没装那个包`danmaku_tools`请见[https://github.com/valkjs/danmaku_tools](https://github.com/valkjsaaa/danmaku_tools)。有问题，去哪里提issue吧。

谢谢大大耐心回复。关于danmaku_tools问题已在那边提问。
