### ISSUE TITLE
运行环境

### ISSUE THREAD

**Issue by silite** [valkjsaaa/auto-bilibili-recorder#23]
因为好多东西都部署在了winServer，所有服务器暂时都是win
修改代码在win上运行，能否给个大致思路。

**Comment by valkjsaaa** [comment]
windows 也可以用 docker 吧

**Comment by valkjsaaa** [comment]
看看 #20 吧

**Comment by silite** [comment]
winServer 2016，各种docker的镜像都很难支持

**Comment by valkjsaaa** [comment]
建议 hyperx + ubuntu 虚拟机
