### ISSUE TITLE
能正常产生文件，但视频上传反复失败，一直重复“上传+失败”

### ISSUE THREAD

**Issue by neko886** [valkjsaaa/auto-bilibili-recorder#25]
Ubuntu Server 18.04.1 LTS 64bit
CPU: 2核 内存: 4GB
（带宽：6Mbps）
录几分钟的小段直播能成功上传，但是录制长时直播，就会上传失败，然后重复上传+失败的过程，持续了一天都没成功。
弹幕、png、MP4等文件都能正常产生。
结尾附有log等文件。
![QQ截图20220601131349](https://user-images.githubusercontent.com/103251269/171332551-7c37d2f7-aa88-4441-908f-38401f220416.jpg)

![QQ截图20220601130948](https://user-images.githubusercontent.com/103251269/171332320-5b0febcc-ba86-422c-8871-9e65bb089362.jpg)
![QQ截图20220601130755](https://user-images.githubusercontent.com/103251269/171332325-eef339b4-fc14-4f3f-9642-a74d529501d7.jpg)
![QQ截图20220601130712](https://user-images.githubusercontent.com/103251269/171332327-0ed8e92d-d7ec-44c7-8192-fc4cd7cfd620.jpg)

[24153980-20220531-180114-919.all.concat.txt](https://github.com/valkjsaaa/auto-bilibili-recorder/files/8811234/24153980-20220531-180114-919.all.concat.txt)
（1kb）
[24153980-20220531-180114-919.all.video.log](https://github.com/valkjsaaa/auto-bilibili-recorder/files/8811235/24153980-20220531-180114-919.all.video.log)  
（4836kb）
[20220531.log](https://github.com/valkjsaaa/auto-bilibili-recorder/files/8811236/20220531.log)
（887kb）

**Comment by neko886** [comment]
经测试发现宽带上行低于15M的上传大视频（1G左右）会不稳定从而导致上传失败。

（另外脚本有时候会持续重复‘try posting subtitle’，中断并重启脚本重启服务器还是会出现‘try posting subtitle’）

因上传不稳定会失败，改用biliup-rs进行上传投稿。

**Comment by valkjsaaa** [comment]
biliup-rs 好像没法换源？要不然我就换 biliup-rs 上传了

**Comment by neko886** [comment]
biliup-rs是没法换源，不过可以追加，感觉先传一次无弹幕版本后再追加有弹幕版本也不错，因为可能有些人不喜欢有弹幕的，会遮挡。要不换来试试？

另外限制宽带流量，让它稳定下来不爆表后也是可以正常使用 auto-bilibili-recorder 的

**Comment by valkjsaaa** [comment]
修好啦。 pull 最新的 master 再试试 🥳
