### ISSUE TITLE
在威联通上运行无反应

### ISSUE THREAD

**Issue by Misaka-Mikoto-Tech** [valkjsaaa/auto-bilibili-recorder#27]
我在威联通的docker里找到auto-bilibili-recorder并安装，把 /storage 映射nas里的一个目录，在里面放置好了 recorder_config.yaml，启动docker后貌似没有工作，控制台没有任何输出，挂载的文件下生成了个 flask.log,输出如下：
* Serving Flask app "/webhook/process_video.py"
* Environment: production
WARNING: This is a development server. Do not use it in a production deployment.
Use a production WSGI server instead.
* Debug mode: off
* Running on http://127.0.0.1:10621/ (Press CTRL+C to quit)

---------------
我用 find 在这个docker里找py文件，发现只有一个 /webhook/process_video.py，但是与github上的文件内容差异很大，请问我是需要自己把github上的文件放进去吗？还是需要什么操作？
相关配置如下：
![image](https://user-images.githubusercontent.com/1246379/177276336-674eaa2f-51b5-4194-b211-0a31113b9ed7.png)
![image](https://user-images.githubusercontent.com/1246379/177276393-b36bc5fe-d6d7-4e9a-8e68-6b61881c2ff6.png)
![image](https://user-images.githubusercontent.com/1246379/177276421-53b949d6-94bc-4a82-8b29-021e62410854.png)
![image](https://user-images.githubusercontent.com/1246379/177276461-0184dba8-2fad-4c62-bbd4-128dd43f3310.png)
![image](https://user-images.githubusercontent.com/1246379/177277085-b3effbc5-ec2a-485b-b0f1-5a8b5f75207a.png)
![image](https://user-images.githubusercontent.com/1246379/177278051-b2fe1fbf-ad95-4a10-8595-5992735df865.png)

**Comment by Misaka-Mikoto-Tech** [comment]
威联通上运行 Bililive-Recorder 是正常的，也能正常录制
![image](https://user-images.githubusercontent.com/1246379/177283605-0d56a43a-6d29-442f-87ad-7158cfe1a82c.png)

**Comment by valkjsaaa** [comment]
> 我在威联通的docker里找到auto-bilibili-recorder并安装，把 /storage 映射nas里的一个目录，在里面放置好了 recorder_config.yaml，启动docker后貌似没有工作，控制台没有任何输出，挂载的文件下生成了个 flask.log,输出如下：
> 
> * Serving Flask app "/webhook/process_video.py"
> * Environment: production
>   WARNING: This is a development server. Do not use it in a production deployment.
>   Use a production WSGI server instead.
> * Debug mode: off
> * Running on http://127.0.0.1:10621/ (Press CTRL+C to quit)
> 
> 我用 find 在这个docker里找py文件，发现只有一个 /webhook/process_video.py，但是与github上的文件内容差异很大，请问我是需要自己把github上的文件放进去吗？还是需要什么操作？ 相关配置如下： ![image](https://user-images.githubusercontent.com/1246379/177276336-674eaa2f-51b5-4194-b211-0a31113b9ed7.png) ![image](https://user-images.githubusercontent.com/1246379/177276393-b36bc5fe-d6d7-4e9a-8e68-6b61881c2ff6.png) ![image](https://user-images.githubusercontent.com/1246379/177276421-53b949d6-94bc-4a82-8b29-021e62410854.png) ![image](https://user-images.githubusercontent.com/1246379/177276461-0184dba8-2fad-4c62-bbd4-128dd43f3310.png) ![image](https://user-images.githubusercontent.com/1246379/177277085-b3effbc5-ec2a-485b-b0f1-5a8b5f75207a.png) ![image](https://user-images.githubusercontent.com/1246379/177278051-b2fe1fbf-ad95-4a10-8595-5992735df865.png)

首先你的 container image 就不对，应该是：ghcr.io/valkjsaaa/auto-bilibili-recorder:master

**Comment by valkjsaaa** [comment]
另外 config 放在文件夹里了吗？

**Comment by Misaka-Mikoto-Tech** [comment]
> 另外 config 放在文件夹里了吗？
![image](https://user-images.githubusercontent.com/1246379/177505419-2d3ca4f0-5376-4f68-b4ba-5cb0bdbc5916.png)


我装的第一个，config文件我看是自动生成的

**Comment by valkjsaaa** [comment]
新版本都是host在github 伤的，压根没上传 docker.com 你得手动指定 image 的地址。

**Comment by valkjsaaa** [comment]
另外 config 得自己写啊，不会自动生成啊？

**Comment by Misaka-Mikoto-Tech** [comment]
![image](https://user-images.githubusercontent.com/1246379/177603885-8f15b2a2-65d5-46d7-af7e-9f1992541fc6.png)

nas的docker没法指定地址，只能在它固定的几个源里搜，或者手动导入 *.tar, *.tar.gz, *.tgz格式的image，目录里的recorder_config.yaml是手写的，config.json 是自动生成的，所以这个 config.json 也是需要手写的吗？

**Comment by valkjsaaa** [comment]
用 qnap 的 命令行吧，我看命令行可以用非 docker.com 上的 image。新版本压根不会用到 config.json

**Comment by Misaka-Mikoto-Tech** [comment]
命令行可以正常安装这个image了，不过能否提供一个选项，不压制高能进度条版的视频？因为现在很多直播间背景墙就显示弹幕姬的画面，高能评论等其它功能可以保留

**Comment by valkjsaaa** [comment]
自己改吧 🤣

**Comment by Misaka-Mikoto-Tech** [comment]
好的
