### ISSUE TITLE
功能建议-同步上传

### ISSUE THREAD

**Issue by by123456by** [valkjsaaa/auto-bilibili-recorder#28]
可以做到录完1p后直接投稿，下1p录完后追加投稿吗
或者每1p录完直接上传，等所有录完后再投稿？

**Comment by ZoidbergPi** [comment]
附议，另外建议可以增加关闭无弹幕版本上传的开关，直接上传高能版，还有就是下方进度条能否更改样式或关闭？

**Comment by valkjsaaa** [comment]
什么叫 1p？

**Comment by valkjsaaa** [comment]
> 附议，另外建议可以增加关闭无弹幕版本上传的开关，直接上传高能版，还有就是下方进度条能否更改样式或关闭？

无弹幕版要是换分辨率或者啥的连不到1p咋办

**Comment by valkjsaaa** [comment]
暂时没有好办法，先关了
