### ISSUE TITLE
长直播带来的视频文件过大问题

### ISSUE THREAD

**Issue by ljpkok** [valkjsaaa/auto-bilibili-recorder#30]
如题所述，当我在录制一场时长为9h 35min的直播时遇到了以下两个问题

1.  B站无法转码 _先行版视频_ 
录制完的.all.flv 文件大小为 39.8GB， 视频成功上传到了B站，但B站提示文件大小超过32GB无法转码。
2.  _高能弹幕版的视频_ 码率过低
压制完的视频文件大小为5.46GB， 码率为1032Kbps， 这种情况可以上传到B站，也可以播放，但是码率过低导致视频效果并不理想。

我理解的压制的视频码率低是根据视频大小动态调整，从而使视频小于上传限制，有没有通过可能将视频分段来解决这一问题?

**Comment by valkjsaaa** [comment]
本来就是动态调整的，取决于你账号的权限，你可以调整这一行代码：

https://github.com/valkjsaaa/auto-bilibili-recorder/blob/60ef38f756ae8fabd67895f79a39b0cdbb2c5f1c/session.py#L260

目前目标是 8G，另外下面第二行为了避免视频超出限制，在基础上由给视频减少了 500k 的码率，可以考虑减少这个值。

分段目前不考虑，因为b站移动端不支持多p视频跳转。合集的话，评论压根就不在一起，也不太合适。
