### ISSUE TITLE
录播后没有生成ass字幕文件和MP4文件，也没有上传

### ISSUE THREAD

**Issue by zhuoyanqiu** [valkjsaaa/auto-bilibili-recorder#31]
* 录播时长：5个多小时
* 服务器环境：腾讯云  CentOS 7.8 64bit  2核  4G
* docker logs 报错信息：
[2022-08-14 22:27:44 +0800] [7] [INFO] 127.0.0.1:59434 POST /process_video 1.1 200 0 2098
[22:27:46 WRN] [] Error running ProcessCommand
System.OverflowException: Value was either too large or too small for an Int32.
   at System.Convert.ThrowInt32OverflowException()
   at System.Convert.ToInt32(Int64 value)
   at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType)
   at Newtonsoft.Json.Linq.JToken.ToObject[T]()
   at BililiveRecorder.Core.Api.Danmaku.DanmakuModel..ctor(String json) in /BililiveRecorder/BililiveRecorder.Core/Api/Danmaku/DanmakuModel.cs:line 236
   at BililiveRecorder.Core.Api.Danmaku.DanmakuClient.ProcessCommand(String json) in /BililiveRecorder/BililiveRecorder.Core/Api/Danmaku/DanmakuClient.cs:line 143

*  bilirec20220814.txt 异常日志
{"@t":"2022-08-14T15:09:00.3165964Z","@mt":"Error running ProcessCommand","@l":"Warning","@x":"System.OverflowException: Value was either too large or too small for an Int32.\n   at System.Convert.ThrowInt32OverflowException()\n   at System.Convert.ToInt32(Int64 value)\n   at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType)\n   at Newtonsoft.Json.Linq.JToken.ToObject[T]()\n   at BililiveRecorder.Core.Api.Danmaku.DanmakuModel..ctor(String json) in /BililiveRecorder/BililiveRecorder.Core/Api/Danmaku/DanmakuModel.cs:line 236\n   at BililiveRecorder.Core.Api.Danmaku.DanmakuClient.ProcessCommand(String json) in /BililiveRecorder/BililiveRecorder.Core/Api/Danmaku/DanmakuClient.cs:line 143","SourceContext":"BililiveRecorder.Core.Api.Danmaku.DanmakuClient","ProcessId":18,"ThreadId":15,"ExceptionDetail":{"Type":"System.OverflowException","HResult":-2146233066,"Message":"Value was either too large or too small for an Int32.","Source":"System.Private.CoreLib"}}

* 生成的文件列表：
-rw-r--r-- 1 root root 10307833630 Aug 14 22:27 941330-20220814-185622-983.flv
-rw-r--r-- 1 root root   486876081 Aug 14 22:27 941330-20220814-185622-983.xml
-rw-r--r-- 1 root root   483679505 Aug 14 22:29 941330-20220814-222731-140.all.clean.xml
-rw-r--r-- 1 root root        1270 Aug 14 22:29 941330-20220814-222731-140.all.extras.log
-rw-r--r-- 1 root root       80563 Aug 14 22:29 941330-20220814-222731-140.all.sc.srt
-rw-r--r-- 1 root root       17404 Aug 14 22:29 941330-20220814-222731-140.all.sc.txt
-rw-r--r-- 1 root root   487707335 Aug 14 22:28 941330-20220814-222731-140.all.xml
-rw-r--r-- 1 root root      116010 Aug 14 22:27 941330-20220814-222731-140.flv
-rw-r--r-- 1 root root       38124 Aug 14 22:27 941330-20220814-222731-140.xml

**Comment by valkjsaaa** [comment]
我知道这个问题了，这个是由于用户 uid 超过 int32 导致的，需要升级内嵌的录播姬版本，我尽量今天发布修复的版本吧

**Comment by valkjsaaa** [comment]
最新版应该解决这个问题了，试试看。
