### ISSUE TITLE
能否帮忙同步更新dockerhub上的镜像？

### ISSUE THREAD

**Issue by Decretum-Wu** [valkjsaaa/auto-bilibili-recorder#35]
如题，国内访问ghcr.io， pull镜像时速度奇慢，并且没找到比较简洁的方法来绕过
然后发现dockerhub上有更新老版本的镜像，那边的访问更加稳定，是否考虑恢复那边的镜像更新呢？

**Comment by Genteure** [comment]
可以试一下 https://dockerproxy.com/

**Comment by valkjsaaa** [comment]
感谢 G 大，更新了 readme @Decretum-Wu 你可以看看

**Comment by Decretum-Wu** [comment]
收到，十分感谢！
