### ISSUE TITLE
获取初始化数据失败

### ISSUE THREAD

**Issue by dogsHappyDay** [valkjsaaa/auto-bilibili-recorder#37]
![image](https://user-images.githubusercontent.com/100328665/189807851-fd95e074-50cb-4958-b2d6-cabb63404922.png)

![image](https://user-images.githubusercontent.com/100328665/189807958-fc1be45e-c927-45b1-8985-4c265774a966.png)

**Comment by valkjsaaa** [comment]
感觉是 upstream 的问题，去这里问问？https://github.com/BililiveRecorder/BililiveRecorder/issues

**Comment by valkjsaaa** [comment]
wait，你这直播间压根不存在啊？
https://live.bilibili.com/237311595

**Comment by dogsHappyDay** [comment]
sry ，刚确认了下房间号错了。抱歉。
