### ISSUE TITLE
修改upload_task.py的上传线路后如何继续使用

### ISSUE THREAD

**Issue by RAINighty** [valkjsaaa/auto-bilibili-recorder#38]
docker看不太懂，不太清楚我本地改完后下一步应该怎么办，求救

**Comment by valkjsaaa** [comment]
理论上来讲，你改完然后 push 到自己的 fork，应该会在你自己的 fork 下生成新的 image，然后你就 docker run 自己生成的 image 就好了

**Comment by RAINighty** [comment]
请问如何push到自己的fork

**Comment by RAINighty** [comment]
/BililiveRecorder/BililiveRecorder.Web/BililiveRecorder.Web.csproj : warning NU1603: BililiveRecorder.Core depends on Jint (>= 3.0.0-preview-275) but Jint 3.0.0-preview-275 was not found. An approximate best match of Jint 3.0.0-preview-293 was resolved. [/BililiveRecorder/BililiveRecorder.Cli/BililiveRecorder.Cli.csproj]
/BililiveRecorder/BililiveRecorder.Core/BililiveRecorder.Core.csproj : warning NU1603: BililiveRecorder.Core depends on Jint (>= 3.0.0-preview-275) but Jint 3.0.0-preview-275 was not found. An approximate best match of Jint 3.0.0-preview-293 was resolved. [/BililiveRecorder/BililiveRecorder.Cli/BililiveRecorder.Cli.csproj]
/BililiveRecorder/BililiveRecorder.Cli/BililiveRecorder.Cli.csproj : warning NU1603: BililiveRecorder.Core depends on Jint (>= 3.0.0-preview-275) but Jint 3.0.0-preview-275 was not found. An approximate best match of Jint 3.0.0-preview-293 was resolved.
/BililiveRecorder/BililiveRecorder.Cli/BililiveRecorder.Cli.csproj : warning NU1603: BililiveRecorder.Core depends on Jint (>= 3.0.0-preview-275) but Jint 3.0.0-preview-275 was not found. An approximate best match of Jint 3.0.0-preview-293 was resolved.
/BililiveRecorder/BililiveRecorder.Core/BililiveRecorder.Core.csproj : warning NU1603: BililiveRecorder.Core depends on Jint (>= 3.0.0-preview-275) but Jint 3.0.0-preview-275 was not found. An approximate best match of Jint 3.0.0-preview-293 was resolved.
/BililiveRecorder/BililiveRecorder.Web/BililiveRecorder.Web.csproj : warning NU1603: BililiveRecorder.Core depends on Jint (>= 3.0.0-preview-275) but Jint 3.0.0-preview-275 was not found. An approximate best match of Jint 3.0.0-preview-293 was resolved.
/BililiveRecorder/BililiveRecorder.Core/Scripting/Runtime/JintFetchSync.cs(23,27): error CS1729: 'JavaScriptException' does not contain a constructor that takes 2 arguments [/BililiveRecorder/BililiveRecorder.Core/BililiveRecorder.Core.csproj]
/BililiveRecorder/BililiveRecorder.Core/Scripting/Runtime/JintFetchSync.cs(26,27): error CS1729: 'JavaScriptException' does not contain a constructor that takes 2 arguments [/BililiveRecorder/BililiveRecorder.Core/BililiveRecorder.Core.csproj]
/BililiveRecorder/BililiveRecorder.Core/Scripting/Runtime/JintFetchSync.cs(31,33): error CS1729: 'JavaScriptException' does not contain a constructor that takes 2 arguments [/BililiveRecorder/BililiveRecorder.Core/BililiveRecorder.Core.csproj]
/BililiveRecorder/BililiveRecorder.Core/Scripting/Runtime/JintFetchSync.cs(78,51): error CS1729: 'JavaScriptException' does not contain a constructor that takes 2 arguments [/BililiveRecorder/BililiveRecorder.Core/BililiveRecorder.Core.csproj]
/BililiveRecorder/BililiveRecorder.Core/Scripting/Runtime/JintFetchSync.cs(108,27): error CS1729: 'JavaScriptException' does not contain a constructor that takes 2 arguments [/BililiveRecorder/BililiveRecorder.Core/BililiveRecorder.Core.csproj]
/BililiveRecorder/BililiveRecorder.Core/Scripting/Runtime/JintFetchSync.cs(167,35): error CS1729: 'JavaScriptException' does not contain a constructor that takes 2 arguments [/BililiveRecorder/BililiveRecorder.Core/BililiveRecorder.Core.csproj]
/BililiveRecorder/BililiveRecorder.Core/Scripting/Runtime/JintFetchSync.cs(178,27): error CS1729: 'JavaScriptException' does not contain a constructor that takes 2 arguments [/BililiveRecorder/BililiveRecorder.Core/BililiveRecorder.Core.csproj]
/BililiveRecorder/BililiveRecorder.Core/Scripting/Runtime/JintFetchSync.cs(188,27): error CS1729: 'JavaScriptException' does not contain a constructor that takes 2 arguments [/BililiveRecorder/BililiveRecorder.Core/BililiveRecorder.Core.csproj]
    6 Warning(s)
    8 Error(s)

Time Elapsed 00:02:21.88
The command '/bin/sh -c dpkgArch="$(uname -m)";     case "$dpkgArch" in         aarch64) export RID='linux-arm64' ;;         x86_64) export RID='linux-x64' ;;         *) export RID='linux-x64' ;;     esac;     dotnet build BililiveRecorder.Cli/BililiveRecorder.Cli.csproj -r $RID -c Release -p:PublishSingleFile=true -p:IncludeNativeLibrariesForSelfExtract=true -p:PublishTrimmed=True -p:TrimMode=Link &&    ln -s /BililiveRecorder/BililiveRecorder.Cli/bin/Release/net6.0/$RID/BililiveRecorder.Cli /BililiveRecorder/BililiveRecorder.Cli/bin/Release/net6.0/' returned a non-zero code: 1

我自己在本地docker build失败了，提示这个

**Comment by Genteure** [comment]
你编译的这个版本的录播姬引用的 Jint 在 MyGet 上被删除了，最简单的解决办法是把录播姬更新到最新版本，修改这一行。

https://github.com/valkjsaaa/auto-bilibili-recorder/blob/0fc648c3cd111372d346854d1ca78ff73b6a2a81/Dockerfile#L30

或者修改录播姬的源码，把引用的 Jint 改成兼容的、在 NuGet 上的版本。

**Comment by RAINighty** [comment]
> https://github.com/BililiveRecorder/BililiveRecorder

将git checkout v2.4.0吗

**Comment by RAINighty** [comment]
> 
应该如何更新呢

**Comment by Genteure** [comment]
对，改成 `git checkout v2.4.0`

**Comment by RAINighty** [comment]
> 对，改成 `git checkout v2.4.0`

改成git checkout v2.4.0后依然报错

**Comment by valkjsaaa** [comment]
好像 v2.4.0 的 jint 也没了，试试 v2.5.0？

**Comment by RAINighty** [comment]
> 2.4.0 用的是 `3.0.0-preview-336` 2.5.0 用的是 `3.0.0-preview-343` 这两个版本都还在
> 
> 上面日志里写的是在尝试下载 `Jint 3.0.0-preview-275` 说明编译的录播姬版本不是 2.4.0

所以我应该咋做

**Comment by RAINighty** [comment]
> 2.4.0 用的是 `3.0.0-preview-336` 2.5.0 用的是 `3.0.0-preview-343` 这两个版本都还在
> 
> 上面日志里写的是在尝试下载 `Jint 3.0.0-preview-275` 说明编译的录播姬版本不是 2.4.0

您好请问我应该如何做，我改成2.5.0也不行

**Comment by RAINighty** [comment]
哦改成2.5.0后突然可以了，已经build succeeded了

**Comment by RAINighty** [comment]
root@yuandatou:~/storage/bilirec# docker run bilirec
nvidia-smi utility not found. Probably driver is not installed.
python3: can't open file '/webhook/process_video.py': [Errno 2] No such file or directory
运行镜像的时候报这个错

**Comment by RAINighty** [comment]
> root@yuandatou:~/storage/bilirec# docker run bilirec nvidia-smi utility not found. Probably driver is not installed. python3: can't open file '/webhook/process_video.py': [Errno 2] No such file or directory 运行镜像的时候报这个错

新建webhook文件夹把其他py文件放进去后重新build可以正常docker run了
