### ISSUE TITLE
有机会添加图形化吗?

### ISSUE THREAD

**Issue by MrZhongzq** [valkjsaaa/auto-bilibili-recorder#39]
b站录播姬是有网页的,不知这边会不会以后添加网页支持,毕竟修改文件还是有点麻烦的.

**Comment by valkjsaaa** [comment]
这个项目只是用 b 站录播姬生成文件，后面的一系列操作需要好多录播姬没有的配置参数，没法使用录播姬的 UI。
我懒，欢迎 PR～
