### ISSUE TITLE
云服务器无GPU用的docker版本的recorder_config.uploader.yaml模板，上传视频是无弹幕版本

### ISSUE THREAD

**Issue by itgoyo** [valkjsaaa/auto-bilibili-recorder#46]
我这边投稿的时候发现在评论区有对应的弹幕时间戳，但是在视频上面并没有看到，请问是我少设置了什么东西么？

对了，投稿标题后面自动带了"无弹幕版"，那如果我想投稿的时候带弹幕高能版呢？是不是只有带GPU的机器才能实现视频带弹幕？感谢百忙之中解答，第一次接触这个项目挺多知识还是不太熟悉。

是不是说高能版本还在转码中，转码成功之后还会自动上传一个高能版本的投稿？

**Comment by valkjsaaa** [comment]
永远会先上传 无弹幕版，同时转码 高能弹幕版，转码完成后 就会上传。

**Comment by valkjsaaa** [comment]
永远会先上传 无弹幕版，同时转码 高能弹幕版，转码完成后 就会上传。

**Comment by itgoyo** [comment]
感谢解惑
