### ISSUE TITLE
掉登录后就无法录制了，且不停的重启

### ISSUE THREAD

**Issue by ZoidbergPi** [valkjsaaa/auto-bilibili-recorder#47]
之前如果掉了登录还是可以进行录制，只是不能上传，现在如果登录失败了就会一直循环尝试进行登录，不会生成录制任务，掉登录是很常见的情况，希望能够把登录和录制流程分开，或者登录不尝试这么多次，毕竟session数据每次修改之后都会重启docker 重试次数太多意义不大，没传上去问题也不大，但是没录上就很痛苦了。。。

**Comment by valkjsaaa** [comment]
有道理，我改了一下，pull 最新版本试一试
