### ISSUE TITLE
启动录制出错 尝试下载直播流时服务器返回了 (NotFound)Not Found

### ISSUE THREAD

**Issue by cj1357** [valkjsaaa/auto-bilibili-recorder#56]
![image](https://user-images.githubusercontent.com/40661342/228713732-18aea25b-e402-4667-ab34-299d83293e60.png)
之前大半年都一直没问题的，今天出现的错误不能录制了，也没有生成相应的日期文件夹

**Comment by valkjsaaa** [comment]
感觉是上游的问题，去这里问问？https://github.com/Bililive/BililiveRecorder

**Comment by cj1357** [comment]
是我这边的问题，好像是被暂时封掉了，停了几个小时，重新跑现在可以了
