### ISSUE TITLE
本项目对录播姬的 session 这个概念的依赖有多大？

### ISSUE THREAD

**Issue by Genteure** [valkjsaaa/auto-bilibili-recorder#61]
最近在研究重构录播姬，添加 HLS 录制支持，重构其中一项是打算去除现在录播姬的 session 这个概念以及对应的 webhook 事件。
本项目现有的处理逻辑应该是在一个 session 结束后继续等一段时间，没有新的 session 后将之前所有的文件拼接到一起，对吧？
所以如果去掉 session 这个概念后，等待的对象就从 session 变成了 file 所以总体上影响不算很大？

**Comment by valkjsaaa** [comment]
嗯，问题不大，本来就考虑了如果两个session很近要合并的问题。以后直接按文件合并即可
