### ISSUE TITLE
recorder_config.yaml报错

### ISSUE THREAD

**Issue by a152917** [valkjsaaa/auto-bilibili-recorder#64]
[root@localhost rec]# ./recorder_config.yaml
./recorder_config.yaml: line 1: $'accounts:\r': command not found
./recorder_config.yaml: line 2: test_bot:: command not found
./recorder_config.yaml: line 3: name:: command not found
./recorder_config.yaml: line 5: sessdata:: command not found
./recorder_config.yaml: line 6: bili_jct:: command not found
./recorder_config.yaml: line 7: line:: command not found
./recorder_config.yaml: line 8: $'rooms:\r': command not found
./recorder_config.yaml: line 9: -: command not found
./recorder_config.yaml: line 10: uploader:: command not found
./recorder_config.yaml: line 11: tags:: command not found
./recorder_config.yaml: line 12: channel_id:: command not found
./recorder_config.yaml: line 13: title:: command not found
./recorder_config.yaml: line 14: source:: command not found
./recorder_config.yaml: line 15: description:: command not found

老哥recorder_config.yaml文件1-15行都报错，系统debian11

**Comment by valkjsaaa** [comment]
跑的方法不对，仔细看 readme
