### ISSUE TITLE
希望能更新下DanmakuFactory版本，DanmakuFactory 1.63 CLI Release版本弹幕间隔有BUG

### ISSUE THREAD

**Issue by ANLzz** [valkjsaaa/auto-bilibili-recorder#65]
https://github.com/hihkm/DanmakuFactory/issues/48

**Comment by lengyanyu258** [comment]
https://github.com/valkjsaaa/auto-bilibili-recorder/blob/108312a20cce6dac06ecd09cb403dd27dd5a3f22/Dockerfile#L53

这里将 `cab7cf813e5322ec3f41431fcae330a800d457a3` 改成新版的 commit SHA 就行，比如 `64213f6af29c95b844c4e46cd07bd5166f7e41c1`

**Comment by ANLzz** [comment]
> https://github.com/valkjsaaa/auto-bilibili-recorder/blob/108312a20cce6dac06ecd09cb403dd27dd5a3f22/Dockerfile#L53
> 
> 这里将`cab7cf813e5322ec3f41431fcae330a800d457a3`改成新版本的commit SHA就行，比如`64213f6af29c95b844c4e46cd07bd5166f7e41c1`

https://github.com/ANLzz/auto-bilibili-recorder/actions/runs/6522101386/job/17711697579 今天建了个分支创建不了Docker Packages 是我昨天建过创过Packages又删了的原因吗

**Comment by lengyanyu258** [comment]
显示是 `403 Forbidden`，我没用过 `ghcr.io`，可能是配置有问题，试试本地创建镜像或是改改配置？

**Comment by ANLzz** [comment]
> 显示是 `403 Forbidden`，我没用过 `ghcr.io`，可能是配置有问题，试试本地创建镜像或是~改改配置~隔一天重新来一次？

https://github.com/ANLzz/auto-bilibili-recorder/actions
镜像解决了，删掉之前建分支的包就可以创了，不过有一些错误启动失败，不会代码看不懂。。。
root@DESKTOP-ON2324D:~# docker logs --tail=200 auto-bilibili-recorder
Traceback (most recent call last):
  File "/webhook/process_video.py", line 1, in <module>
    from quart import Quart, request, Response
  File "/usr/local/lib/python3.8/dist-packages/quart/__init__.py", line 5, in <module>
    from .app import Quart as Quart
  File "/usr/local/lib/python3.8/dist-packages/quart/app.py", line 46, in <module>
    from werkzeug.urls import url_quote
ImportError: cannot import name 'url_quote' from 'werkzeug.urls' (/usr/local/lib/python3.8/dist-packages/werkzeug/urls.py)
Detected nvidia driver version: 531.79
Patch for this (531.79) nvidia driver not found.
Patch is available for versions:

**Comment by lengyanyu258** [comment]
可能是环境不同导致版本不一致产生的问题，比如 Python 版本比较新或是 Nvidia 驱动版本过于新……

**Comment by ANLzz** [comment]
> 可能是环境不同导致版本不一致产生的问题，比如 Python 版本比较新或是 Nvidia 驱动版本过于新……

Python Nvidia 驱动相同环境，下载https://github.com/a0071234c/auto-bilibili-recorder这个镜像用着正常，我在这个分支上再分支把DanmakuFactory改成 1.7的生成镜像就不行了。。。

**Comment by cj1357** [comment]
> https://github.com/ANLzz/auto-bilibili-recorder/actions 镜像解决了，删掉之前建分支的包就可以创了，不过有一些错误启动失败，不会代码看不懂。。。 root@DESKTOP-ON2324D:~# docker logs --tail=200 auto-bilibili-recorder Traceback (most recent call last): File "/webhook/process_video.py", line 1, in from quart import Quart, request, Response File "/usr/local/lib/python3.8/dist-packages/quart/**init**.py", line 5, in from .app import Quart as Quart File "/usr/local/lib/python3.8/dist-packages/quart/app.py", line 46, in from werkzeug.urls import url_quote ImportError: cannot import name 'url_quote' from 'werkzeug.urls' (/usr/local/lib/python3.8/dist-packages/werkzeug/urls.py) Detected nvidia driver version: 531.79 Patch for this (531.79) nvidia driver not found. Patch is available for versions:

看到过这种问题：
https://stackoverflow.com/questions/77213053/importerror-cannot-import-name-url-quote-from-werkzeug-urls
在requirements.txt里面限制Werkzeug==2.2.2应该就好了
