### ISSUE TITLE
使用 `mp4` 文件显著提升压制速度

### ISSUE THREAD

**Issue by lengyanyu258** [valkjsaaa/auto-bilibili-recorder#66]
https://github.com/valkjsaaa/auto-bilibili-recorder/blob/108312a20cce6dac06ecd09cb403dd27dd5a3f22/session.py#L268-L270

好像使用整理后（`-c copy`）的单个 `mp4` 文件能显著提升压制速度（`FFmpeg` 能跑满显卡）：

```python
input_video = (
    f" -i \"{self.output_paths()['early_video']}\""
    if os.path.exists(self.output_paths()["early_video"])
    else f"-f concat -safe 0 -i \"{self.output_paths()['concat_file']}\""
)
```

不知道这里是否需要改成 `.mp4`（没试过）：

https://github.com/valkjsaaa/auto-bilibili-recorder/blob/108312a20cce6dac06ecd09cb403dd27dd5a3f22/session.py#L134

---

可能也与这个有关：

https://github.com/valkjsaaa/auto-bilibili-recorder/blob/108312a20cce6dac06ecd09cb403dd27dd5a3f22/session.py#L292

将 `-b:a 320K -ar 44100` 改为 `-c:a copy`

**Comment by lengyanyu258** [comment]
也许只是错觉。

**Comment by lengyanyu258** [comment]
有人试试吗😏（貌似有作用🤔）

**Comment by valkjsaaa** [comment]
音频我特意设置的一个固定编码率，是因为有的时候主播中间切换了音频编码。理论上来讲视频压缩应该工作量远远大于音频。你自己使用的时候有明显区别吗？

**Comment by valkjsaaa** [comment]
没有用 mp4 是有的时候碎得太厉害的时候的 mp4 文件本身播不了，为了稳定还是用那个 concat.txt 吧
