### ISSUE TITLE
Web API not enabled

### ISSUE THREAD

**Issue by mengwei1** [valkjsaaa/auto-bilibili-recorder#68]
我按照Readme配置了配置文件，启动了docker镜像，然后通过docker logs <id>查看日志。

nvidia-smi utility not found. Probably driver is not installed.
{'name': 马赛克, 'sessdata': 马赛克, 'bili_jct': 马赛克, 'line': 'bup', 'access_token': ''}
使用cookies上传
验证 cookie 成功: 马赛克
login successfully! 马赛克  马赛克 马赛克
spawn recorder for 马赛克: /BililiveRecorder/BililiveRecorder.Cli/bin/Release/net6.0/BililiveRecorder.Cli portable -d 63 --webhook-url "http://127.0.0.1:10261/process_video" --filename "{{ roomId }}/{{ \"now\" | time_zone: \"Asia/Shanghai\" | format_date: \"yyyyMMdd\" }}/{{ roomId }}-{{ \"now\" | time_zone: \"Asia/Shanghai\" | format_date: \"yyyyMMdd-HHmmss-fff\" }}.flv" /storage/ 马赛克 
spawn recorder for 马赛克: /BililiveRecorder/BililiveRecorder.Cli/bin/Release/net6.0/BililiveRecorder.Cli portable -d 63 --webhook-url "http://127.0.0.1:10261/process_video" --filename "{{ roomId }}/{{ \"now\" | time_zone: \"Asia/Shanghai\" | format_date: \"yyyyMMdd\" }}/{{ roomId }}-{{ \"now\" | time_zone: \"Asia/Shanghai\" | format_date: \"yyyyMMdd-HHmmss-fff\" }}.flv" /storage/ 马赛克 
spawn recorder for 马赛克: /BililiveRecorder/BililiveRecorder.Cli/bin/Release/net6.0/BililiveRecorder.Cli portable -d 63 --webhook-url "http://127.0.0.1:10261/process_video" --filename "{{ roomId }}/{{ \"now\" | time_zone: \"Asia/Shanghai\" | format_date: \"yyyyMMdd\" }}/{{ roomId }}-{{ \"now\" | time_zone: \"Asia/Shanghai\" | format_date: \"yyyyMMdd-HHmmss-fff\" }}.flv" /storage/ 马赛克 
spawn recorder for 马赛克: /BililiveRecorder/BililiveRecorder.Cli/bin/Release/net6.0/BililiveRecorder.Cli portable -d 63 --webhook-url "http://127.0.0.1:10261/process_video" --filename "{{ roomId }}/{{ \"now\" | time_zone: \"Asia/Shanghai\" | format_date: \"yyyyMMdd\" }}/{{ roomId }}-{{ \"now\" | time_zone: \"Asia/Shanghai\" | format_date: \"yyyyMMdd-HHmmss-fff\" }}.flv" /storage/ 马赛克 
 * Serving Quart app 'process_video'
 * Environment: production
 * Please use an ASGI server (e.g. Hypercorn) directly in production
 * Debug mode: False
 * Running on http://127.0.0.1:10261 (CTRL + C to quit)
[2023-11-29 14:13:08 +0800] [6] [INFO] Running on http://127.0.0.1:10261 (CTRL + C to quit)
[14:13:09 INF] Web API not enabled
[14:13:09 INF] Web API not enabled
[14:13:09 INF] Web API not enabled
[14:13:09 INF] Web API not enabled
[14:13:11 INF (BililiveRecorder.Core.Room)] [马赛克] 弹幕服务器已连接
[14:13:11 INF (BililiveRecorder.Core.Room)] [马赛克] 弹幕服务器已连接
[14:13:11 INF (BililiveRecorder.Core.Room)] [马赛克] 弹幕服务器已连接
[14:13:11 INF (BililiveRecorder.Core.Room)] [马赛克] 弹幕服务器已连接

根据日志，可以看到我的录播账号成功登录，房间设置也生效了，但是我
1.使用浏览器访问该机器10261端口（防火墙已放通）
2.该机器命令行curl 127.0.0.1:10261
都没有返回，请问这个端口是监控/后台/状态接口吗？是给人用的吗？
如果我想查看日志，或者当前的运行状态，应该怎么操作？

**Comment by cj1357** [comment]
参考B站录播姬的文档-命令行参数：”指定录播姬 HTTP 服务的监听地址，如果不指定则不启动 HTTP 服务“
https://rec.danmuji.org/reference/arguments/

https://github.com/valkjsaaa/auto-bilibili-recorder/blob/108312a20cce6dac06ecd09cb403dd27dd5a3f22/recorder_manager.py#L11
在这里可以添加一行代码绑定，以启动Web API：（供参考）
f'--bind "http://*:8900" --http-basic-user "cj1357" --http-basic-pass "123456" ' \

注意绑定的是容器内的端口号（可以自己换），用docker启动需要添加参数-p 8900:8900

启动后就可以通过 http://localhost:8900 访问当前运行的录播姬webui了

**Comment by mengwei1** [comment]
非常感谢，我会尝试的发自我的手机-------- 原始邮件 --------发件人： cj1357 ***@***.***>日期： 2024年1月2日周二 晚上7:32收件人： valkjsaaa/auto-bilibili-recorder ***@***.***>抄送： Wei Meng ***@***.***>, State change ***@***.***>主    题： Re: [valkjsaaa/auto-bilibili-recorder] Web API not enabled (Issue #68)
参考B站录播姬的文档-命令行参数：”指定录播姬 HTTP 服务的监听地址，如果不指定则不启动 HTTP 服务“
https://rec.danmuji.org/reference/arguments/
https://github.com/valkjsaaa/auto-bilibili-recorder/blob/108312a20cce6dac06ecd09cb403dd27dd5a3f22/recorder_manager.py#L11
在这里可以添加一行代码绑定，以启动Web API：（供参考）
f'--bind "http://*:8900" --http-basic-user "cj1357" --http-basic-pass "123456" ' \
注意绑定的是容器内的端口号（可以自己换），用docker启动需要添加参数-p 8900:8900
启动后就可以通过 http://localhost:8900 访问当前运行的录播姬webui了
