### ISSUE TITLE
跨日直播断流导致上传不完整

### ISSUE THREAD

**Issue by Shiori514** [valkjsaaa/auto-bilibili-recorder#8]
版本3.11

假设有一段直播是1月1日23:00到1月2日1:00。

如果1月1日23:30和1月2日0:30各断流一次，总共分了三段。

那么23:00-0:30的两段被分到0101的文件夹内，0:30-1:00的部分被分到0102的文件夹内，合并时只会合并前两段，只上传前两段，1月2日0:30-1:00的部分会被忽略。

**Comment by valkjsaaa** [comment]
存储的文件夹应该和合并的机制没关系。你发个 docker 的 log 看看吧。我目测分成两段的原因是因为主播断开的时间超过了5分钟。

**Comment by Shiori514** [comment]
先看了一下录播的 log ，并不是主播断流……是主动断开重连的，间隔大概10秒（时区是UTC0）
> {"@t":"2021-07-10T16:16:31.1502502Z","@mt":"Networking stats: {@stats}","@l":"Verbose","stats":{"StartTime":"2021-07-10T16:16:29.1496766+00:00","EndTime":"2021-07-10T16:16:31.1501954+00:00","Duration":"00:00:02.0005188","BytesDownloaded":1372208,"Mbps":5.233200613229678,"$type":"NetworkingStatsEventArgs"},"RoomId":22603245,"SourceContext":"BililiveRecorder.Core.Room","ProcessId":11,"ThreadId":36}
{"@t":"2021-07-10T16:16:33.1498876Z","@mt":"Networking stats: {@stats}","@l":"Verbose","stats":{"StartTime":"2021-07-10T16:16:31.1501954+00:00","EndTime":"2021-07-10T16:16:33.1498191+00:00","Duration":"00:00:01.9996237","BytesDownloaded":630792,"Mbps":2.406733344456885,"$type":"NetworkingStatsEventArgs"},"RoomId":22603245,"SourceContext":"BililiveRecorder.Core.Room","ProcessId":11,"ThreadId":64}
{"@t":"2021-07-10T16:16:35.1492352Z","@mt":"Networking stats: {@stats}","@l":"Verbose","stats":{"StartTime":"2021-07-10T16:16:33.1498191+00:00","EndTime":"2021-07-10T16:16:35.1491802+00:00","Duration":"00:00:01.9993611","BytesDownloaded":0,"Mbps":0,"$type":"NetworkingStatsEventArgs"},"RoomId":22603245,"SourceContext":"BililiveRecorder.Core.Room","ProcessId":11,"ThreadId":64}
{"@t":"2021-07-10T16:16:37.1540908Z","@mt":"Networking stats: {@stats}","@l":"Verbose","stats":{"StartTime":"2021-07-10T16:16:35.1491802+00:00","EndTime":"2021-07-10T16:16:37.1540325+00:00","Duration":"00:00:02.0048523","BytesDownloaded":0,"Mbps":0,"$type":"NetworkingStatsEventArgs"},"RoomId":22603245,"SourceContext":"BililiveRecorder.Core.Room","ProcessId":11,"ThreadId":64}
{"@t":"2021-07-10T16:16:39.1536641Z","@mt":"Networking stats: {@stats}","@l":"Verbose","stats":{"StartTime":"2021-07-10T16:16:37.1540325+00:00","EndTime":"2021-07-10T16:16:39.1535974+00:00","Duration":"00:00:01.9995649","BytesDownloaded":0,"Mbps":0,"$type":"NetworkingStatsEventArgs"},"RoomId":22603245,"SourceContext":"BililiveRecorder.Core.Room","ProcessId":11,"ThreadId":64}
{"@t":"2021-07-10T16:16:41.1536320Z","@mt":"Networking stats: {@stats}","@l":"Verbose","stats":{"StartTime":"2021-07-10T16:16:39.1535974+00:00","EndTime":"2021-07-10T16:16:41.1535692+00:00","Duration":"00:00:01.9999718","BytesDownloaded":0,"Mbps":0,"$type":"NetworkingStatsEventArgs"},"RoomId":22603245,"SourceContext":"BililiveRecorder.Core.Room","ProcessId":11,"ThreadId":64}
{"@t":"2021-07-10T16:16:43.1542229Z","@mt":"Networking stats: {@stats}","@l":"Verbose","stats":{"StartTime":"2021-07-10T16:16:41.1535692+00:00","EndTime":"2021-07-10T16:16:43.1541642+00:00","Duration":"00:00:02.0005950","BytesDownloaded":0,"Mbps":0,"$type":"NetworkingStatsEventArgs"},"RoomId":22603245,"SourceContext":"BililiveRecorder.Core.Room","ProcessId":11,"ThreadId":64}
{"@t":"2021-07-10T16:16:43.1545348Z","@mt":"直播服务器未断开连接但停止发送直播数据，将会主动断开连接","@l":"Warning","RoomId":22603245,"SourceContext":"BililiveRecorder.Core.Recording.StandardRecordTask","ProcessId":11,"ThreadId":64}
{"@t":"2021-07-10T16:16:43.1556287Z","@mt":"录制被取消","@l":"Debug","@x":"System.OperationCanceledException: The operation was canceled.\n   at System.Threading.CancellationToken.ThrowOperationCanceledException()\n   at System.IO.Pipelines.Pipe.GetReadAsyncResult()\n   at BililiveRecorder.Flv.Parser.FlvTagPipeReader.ReadNextTagAsync(CancellationToken cancellationToken) in /BililiveRecorder/BililiveRecorder.Flv/Parser/FlvTagPipeReader.cs:line 64\n   at BililiveRecorder.Flv.Parser.FlvTagPipeReader.ReadTagAsync(CancellationToken token) in /BililiveRecorder/BililiveRecorder.Flv/Parser/FlvTagPipeReader.cs:line 349\n   at BililiveRecorder.Flv.Grouping.TagGroupReader.ReadGroupAsync(CancellationToken token) in /BililiveRecorder/BililiveRecorder.Flv/Grouping/TagGroupReader.cs:line 91\n   at BililiveRecorder.Core.Recording.StandardRecordTask.RecordingLoopAsync() in /BililiveRecorder/BililiveRecorder.Core/Recording/StandardRecordTask.cs:line 158","RoomId":22603245,"SourceContext":"BililiveRecorder.Core.Recording.StandardRecordTask","ProcessId":11,"ThreadId":19,"ExceptionDetail":{"Type":"System.OperationCanceledException","HResult":-2146233029,"Message":"The operation was canceled.","Source":"System.Private.CoreLib","CancellationToken":"CancellationRequested: true"}}
{"@t":"2021-07-10T16:16:43.1591167Z","@mt":"录制结束","RoomId":22603245,"SourceContext":"BililiveRecorder.Core.Recording.StandardRecordTask","ProcessId":11,"ThreadId":19}
{"@t":"2021-07-10T16:16:43.4512348Z","@mt":"Create record task with mode {RecordMode} for room {RoomId}","@l":"Debug","RecordMode":"Standard","RoomId":22603245,"SourceContext":"BililiveRecorder.Core.Recording.RecordTaskFactory","ProcessId":11,"ThreadId":58}
{"@t":"2021-07-10T16:16:43.5966363Z","@mt":"连接直播服务器 {Host}","Host":"cn-jsnt-cmcc-live-02.bilivideo.com","RoomId":22603245,"SourceContext":"BililiveRecorder.Core.Recording.StandardRecordTask","ProcessId":11,"ThreadId":19}
{"@t":"2021-07-10T16:16:43.5973707Z","@mt":"直播流地址 {Url}","@l":"Debug","Url":"https://cn-jsnt-cmcc-live-02.bilivideo.com/live-bvc/297100/live_1265680561_8885980.flv?expires=1625937463&len=0&oi=3745523649&pt=web&qn=10000&trid=100081b7b30793684a898f352f2d93338d95&sigparams=cdn,expires,len,oi,pt,qn,trid&cdn=cn-gotcha01&sign=341c9ff929a301931aaee9279458253c&p2p_type=1&src=9&sl=3&free_type=0&sk=417e709c171a500&sid=9886","RoomId":22603245,"SourceContext":"BililiveRecorder.Core.Recording.StandardRecordTask","ProcessId":11,"ThreadId":19}
{"@t":"2021-07-10T16:16:43.8018999Z","@mt":"开始接收直播流","RoomId":22603245,"SourceContext":"BililiveRecorder.Core.Recording.StandardRecordTask","ProcessId":11,"ThreadId":19}
{"@t":"2021-07-10T16:16:43.8029206Z","@mt":"Recording stats: {@stats}","@l":"Verbose","stats":{"InputVideoByteCount":0,"InputAudioByteCount":0,"OutputVideoFrameCount":0,"OutputAudioFrameCount":0,"OutputVideoByteCount":0,"OutputAudioByteCount":0,"TotalInputVideoByteCount":0,"TotalInputAudioByteCount":0,"TotalOutputVideoFrameCount":0,"TotalOutputAudioFrameCount":0,"TotalOutputVideoByteCount":0,"TotalOutputAudioByteCount":0,"CurrnetFileSize":0,"AddedDuration":0,"PassedTime":63761530603.80269,"DuraionRatio":0,"SessionMaxTimestamp":0,"FileMaxTimestamp":0,"$type":"RecordingStatsEventArgs"},"RoomId":22603245,"SourceContext":"BililiveRecorder.Core.Room","ProcessId":11,"ThreadId":51}
{"@t":"2021-07-10T16:16:43.8032644Z","@mt":"修复逻辑输出 {@Comments}","@l":"Debug","Comments":[{"T":"Logging","C":"收到了 onMetaData","$type":"ProcessingComment"}],"RoomId":22603245,"SourceContext":"BililiveRecorder.Core.Recording.StandardRecordTask","ProcessId":11,"ThreadId":51}
{"@t":"2021-07-10T16:16:43.8199326Z","@mt":"Recording stats: {@stats}","@l":"Verbose","stats":{"InputVideoByteCount":0,"InputAudioByteCount":0,"OutputVideoFrameCount":0,"OutputAudioFrameCount":0,"OutputVideoByteCount":0,"OutputAudioByteCount":0,"TotalInputVideoByteCount":0,"TotalInputAudioByteCount":0,"TotalOutputVideoFrameCount":0,"TotalOutputAudioFrameCount":0,"TotalOutputVideoByteCount":0,"TotalOutputAudioByteCount":0,"CurrnetFileSize":0,"AddedDuration":0,"PassedTime":0.0171673,"DuraionRatio":0,"SessionMaxTimestamp":0,"FileMaxTimestamp":0,"$type":"RecordingStatsEventArgs"},"RoomId":22603245,"SourceContext":"BililiveRecorder.Core.Room","ProcessId":11,"ThreadId":58}
{"@t":"2021-07-10T16:16:43.8717179Z","@mt":"Recording stats: {@stats}","@l":"Verbose","stats":{"InputVideoByteCount":2541147,"InputAudioByteCount":137062,"OutputVideoFrameCount":250,"OutputAudioFrameCount":195,"OutputVideoByteCount":2166467,"OutputAudioByteCount":137062,"TotalInputVideoByteCount":2541147,"TotalInputAudioByteCount":137062,"TotalOutputVideoFrameCount":250,"TotalOutputAudioFrameCount":195,"TotalOutputVideoByteCount":2166467,"TotalOutputAudioByteCount":137062,"CurrnetFileSize":2303542,"AddedDuration":4.153,"PassedTime":0.0517661,"DuraionRatio":80.22624845217236,"SessionMaxTimestamp":4153,"FileMaxTimestamp":4153,"$type":"RecordingStatsEventArgs"},"RoomId":22603245,"SourceContext":"BililiveRecorder.Core.Room","ProcessId":11,"ThreadId":19}
{"@t":"2021-07-10T16:16:43.8721233Z","@mt":"修复逻辑输出 {@Comments}","@l":"Debug","Comments":[{"T":"TimestampJump","C":"时间戳间隔过大, curr: 4091666, diff: 4091666","$type":"ProcessingComment"}],"RoomId":22603245,"SourceContext":"BililiveRecorder.Core.Recording.StandardRecordTask","ProcessId":11,"ThreadId":19}
{"@t":"2021-07-10T16:16:43.8888717Z","@mt":"新建录制文件 {Path}","Path":"/storage/22603245/20210711/22603245-20210711-001643-872.flv","RoomId":22603245,"SourceContext":"BililiveRecorder.Core.Recording.StandardRecordTask","ProcessId":11,"ThreadId":19}
{"@t":"2021-07-10T16:16:45.8025440Z","@mt":"Networking stats: {@stats}","@l":"Verbose","stats":{"StartTime":"2021-07-10T16:16:43.8024756+00:00","EndTime":"2021-07-10T16:16:45.8024119+00:00","Duration":"00:00:01.9999363","BytesDownloaded":4930251,"Mbps":18.808014043792216,"$type":"NetworkingStatsEventArgs"},"RoomId":22603245,"SourceContext":"BililiveRecorder.Core.Room","ProcessId":11,"ThreadId":51}

**Comment by Shiori514** [comment]
先看了一下录播的 log ，并不是主播断流……是主动断开重连的，间隔大概10秒（时区是UTC0）
> {"@t":"2021-07-10T16:16:31.1502502Z","@mt":"Networking stats: {@stats}","@l":"Verbose","stats":{"StartTime":"2021-07-10T16:16:29.1496766+00:00","EndTime":"2021-07-10T16:16:31.1501954+00:00","Duration":"00:00:02.0005188","BytesDownloaded":1372208,"Mbps":5.233200613229678,"$type":"NetworkingStatsEventArgs"},"RoomId":22603245,"SourceContext":"BililiveRecorder.Core.Room","ProcessId":11,"ThreadId":36}
{"@t":"2021-07-10T16:16:33.1498876Z","@mt":"Networking stats: {@stats}","@l":"Verbose","stats":{"StartTime":"2021-07-10T16:16:31.1501954+00:00","EndTime":"2021-07-10T16:16:33.1498191+00:00","Duration":"00:00:01.9996237","BytesDownloaded":630792,"Mbps":2.406733344456885,"$type":"NetworkingStatsEventArgs"},"RoomId":22603245,"SourceContext":"BililiveRecorder.Core.Room","ProcessId":11,"ThreadId":64}
{"@t":"2021-07-10T16:16:35.1492352Z","@mt":"Networking stats: {@stats}","@l":"Verbose","stats":{"StartTime":"2021-07-10T16:16:33.1498191+00:00","EndTime":"2021-07-10T16:16:35.1491802+00:00","Duration":"00:00:01.9993611","BytesDownloaded":0,"Mbps":0,"$type":"NetworkingStatsEventArgs"},"RoomId":22603245,"SourceContext":"BililiveRecorder.Core.Room","ProcessId":11,"ThreadId":64}
{"@t":"2021-07-10T16:16:37.1540908Z","@mt":"Networking stats: {@stats}","@l":"Verbose","stats":{"StartTime":"2021-07-10T16:16:35.1491802+00:00","EndTime":"2021-07-10T16:16:37.1540325+00:00","Duration":"00:00:02.0048523","BytesDownloaded":0,"Mbps":0,"$type":"NetworkingStatsEventArgs"},"RoomId":22603245,"SourceContext":"BililiveRecorder.Core.Room","ProcessId":11,"ThreadId":64}
{"@t":"2021-07-10T16:16:39.1536641Z","@mt":"Networking stats: {@stats}","@l":"Verbose","stats":{"StartTime":"2021-07-10T16:16:37.1540325+00:00","EndTime":"2021-07-10T16:16:39.1535974+00:00","Duration":"00:00:01.9995649","BytesDownloaded":0,"Mbps":0,"$type":"NetworkingStatsEventArgs"},"RoomId":22603245,"SourceContext":"BililiveRecorder.Core.Room","ProcessId":11,"ThreadId":64}
{"@t":"2021-07-10T16:16:41.1536320Z","@mt":"Networking stats: {@stats}","@l":"Verbose","stats":{"StartTime":"2021-07-10T16:16:39.1535974+00:00","EndTime":"2021-07-10T16:16:41.1535692+00:00","Duration":"00:00:01.9999718","BytesDownloaded":0,"Mbps":0,"$type":"NetworkingStatsEventArgs"},"RoomId":22603245,"SourceContext":"BililiveRecorder.Core.Room","ProcessId":11,"ThreadId":64}
{"@t":"2021-07-10T16:16:43.1542229Z","@mt":"Networking stats: {@stats}","@l":"Verbose","stats":{"StartTime":"2021-07-10T16:16:41.1535692+00:00","EndTime":"2021-07-10T16:16:43.1541642+00:00","Duration":"00:00:02.0005950","BytesDownloaded":0,"Mbps":0,"$type":"NetworkingStatsEventArgs"},"RoomId":22603245,"SourceContext":"BililiveRecorder.Core.Room","ProcessId":11,"ThreadId":64}
{"@t":"2021-07-10T16:16:43.1545348Z","@mt":"直播服务器未断开连接但停止发送直播数据，将会主动断开连接","@l":"Warning","RoomId":22603245,"SourceContext":"BililiveRecorder.Core.Recording.StandardRecordTask","ProcessId":11,"ThreadId":64}
{"@t":"2021-07-10T16:16:43.1556287Z","@mt":"录制被取消","@l":"Debug","@x":"System.OperationCanceledException: The operation was canceled.\n   at System.Threading.CancellationToken.ThrowOperationCanceledException()\n   at System.IO.Pipelines.Pipe.GetReadAsyncResult()\n   at BililiveRecorder.Flv.Parser.FlvTagPipeReader.ReadNextTagAsync(CancellationToken cancellationToken) in /BililiveRecorder/BililiveRecorder.Flv/Parser/FlvTagPipeReader.cs:line 64\n   at BililiveRecorder.Flv.Parser.FlvTagPipeReader.ReadTagAsync(CancellationToken token) in /BililiveRecorder/BililiveRecorder.Flv/Parser/FlvTagPipeReader.cs:line 349\n   at BililiveRecorder.Flv.Grouping.TagGroupReader.ReadGroupAsync(CancellationToken token) in /BililiveRecorder/BililiveRecorder.Flv/Grouping/TagGroupReader.cs:line 91\n   at BililiveRecorder.Core.Recording.StandardRecordTask.RecordingLoopAsync() in /BililiveRecorder/BililiveRecorder.Core/Recording/StandardRecordTask.cs:line 158","RoomId":22603245,"SourceContext":"BililiveRecorder.Core.Recording.StandardRecordTask","ProcessId":11,"ThreadId":19,"ExceptionDetail":{"Type":"System.OperationCanceledException","HResult":-2146233029,"Message":"The operation was canceled.","Source":"System.Private.CoreLib","CancellationToken":"CancellationRequested: true"}}
{"@t":"2021-07-10T16:16:43.1591167Z","@mt":"录制结束","RoomId":22603245,"SourceContext":"BililiveRecorder.Core.Recording.StandardRecordTask","ProcessId":11,"ThreadId":19}
{"@t":"2021-07-10T16:16:43.4512348Z","@mt":"Create record task with mode {RecordMode} for room {RoomId}","@l":"Debug","RecordMode":"Standard","RoomId":22603245,"SourceContext":"BililiveRecorder.Core.Recording.RecordTaskFactory","ProcessId":11,"ThreadId":58}
{"@t":"2021-07-10T16:16:43.5966363Z","@mt":"连接直播服务器 {Host}","Host":"cn-jsnt-cmcc-live-02.bilivideo.com","RoomId":22603245,"SourceContext":"BililiveRecorder.Core.Recording.StandardRecordTask","ProcessId":11,"ThreadId":19}
{"@t":"2021-07-10T16:16:43.5973707Z","@mt":"直播流地址 {Url}","@l":"Debug","Url":"https://cn-jsnt-cmcc-live-02.bilivideo.com/live-bvc/297100/live_1265680561_8885980.flv?expires=1625937463&len=0&oi=3745523649&pt=web&qn=10000&trid=100081b7b30793684a898f352f2d93338d95&sigparams=cdn,expires,len,oi,pt,qn,trid&cdn=cn-gotcha01&sign=341c9ff929a301931aaee9279458253c&p2p_type=1&src=9&sl=3&free_type=0&sk=417e709c171a500&sid=9886","RoomId":22603245,"SourceContext":"BililiveRecorder.Core.Recording.StandardRecordTask","ProcessId":11,"ThreadId":19}
{"@t":"2021-07-10T16:16:43.8018999Z","@mt":"开始接收直播流","RoomId":22603245,"SourceContext":"BililiveRecorder.Core.Recording.StandardRecordTask","ProcessId":11,"ThreadId":19}
{"@t":"2021-07-10T16:16:43.8029206Z","@mt":"Recording stats: {@stats}","@l":"Verbose","stats":{"InputVideoByteCount":0,"InputAudioByteCount":0,"OutputVideoFrameCount":0,"OutputAudioFrameCount":0,"OutputVideoByteCount":0,"OutputAudioByteCount":0,"TotalInputVideoByteCount":0,"TotalInputAudioByteCount":0,"TotalOutputVideoFrameCount":0,"TotalOutputAudioFrameCount":0,"TotalOutputVideoByteCount":0,"TotalOutputAudioByteCount":0,"CurrnetFileSize":0,"AddedDuration":0,"PassedTime":63761530603.80269,"DuraionRatio":0,"SessionMaxTimestamp":0,"FileMaxTimestamp":0,"$type":"RecordingStatsEventArgs"},"RoomId":22603245,"SourceContext":"BililiveRecorder.Core.Room","ProcessId":11,"ThreadId":51}
{"@t":"2021-07-10T16:16:43.8032644Z","@mt":"修复逻辑输出 {@Comments}","@l":"Debug","Comments":[{"T":"Logging","C":"收到了 onMetaData","$type":"ProcessingComment"}],"RoomId":22603245,"SourceContext":"BililiveRecorder.Core.Recording.StandardRecordTask","ProcessId":11,"ThreadId":51}
{"@t":"2021-07-10T16:16:43.8199326Z","@mt":"Recording stats: {@stats}","@l":"Verbose","stats":{"InputVideoByteCount":0,"InputAudioByteCount":0,"OutputVideoFrameCount":0,"OutputAudioFrameCount":0,"OutputVideoByteCount":0,"OutputAudioByteCount":0,"TotalInputVideoByteCount":0,"TotalInputAudioByteCount":0,"TotalOutputVideoFrameCount":0,"TotalOutputAudioFrameCount":0,"TotalOutputVideoByteCount":0,"TotalOutputAudioByteCount":0,"CurrnetFileSize":0,"AddedDuration":0,"PassedTime":0.0171673,"DuraionRatio":0,"SessionMaxTimestamp":0,"FileMaxTimestamp":0,"$type":"RecordingStatsEventArgs"},"RoomId":22603245,"SourceContext":"BililiveRecorder.Core.Room","ProcessId":11,"ThreadId":58}
{"@t":"2021-07-10T16:16:43.8717179Z","@mt":"Recording stats: {@stats}","@l":"Verbose","stats":{"InputVideoByteCount":2541147,"InputAudioByteCount":137062,"OutputVideoFrameCount":250,"OutputAudioFrameCount":195,"OutputVideoByteCount":2166467,"OutputAudioByteCount":137062,"TotalInputVideoByteCount":2541147,"TotalInputAudioByteCount":137062,"TotalOutputVideoFrameCount":250,"TotalOutputAudioFrameCount":195,"TotalOutputVideoByteCount":2166467,"TotalOutputAudioByteCount":137062,"CurrnetFileSize":2303542,"AddedDuration":4.153,"PassedTime":0.0517661,"DuraionRatio":80.22624845217236,"SessionMaxTimestamp":4153,"FileMaxTimestamp":4153,"$type":"RecordingStatsEventArgs"},"RoomId":22603245,"SourceContext":"BililiveRecorder.Core.Room","ProcessId":11,"ThreadId":19}
{"@t":"2021-07-10T16:16:43.8721233Z","@mt":"修复逻辑输出 {@Comments}","@l":"Debug","Comments":[{"T":"TimestampJump","C":"时间戳间隔过大, curr: 4091666, diff: 4091666","$type":"ProcessingComment"}],"RoomId":22603245,"SourceContext":"BililiveRecorder.Core.Recording.StandardRecordTask","ProcessId":11,"ThreadId":19}
{"@t":"2021-07-10T16:16:43.8888717Z","@mt":"新建录制文件 {Path}","Path":"/storage/22603245/20210711/22603245-20210711-001643-872.flv","RoomId":22603245,"SourceContext":"BililiveRecorder.Core.Recording.StandardRecordTask","ProcessId":11,"ThreadId":19}
{"@t":"2021-07-10T16:16:45.8025440Z","@mt":"Networking stats: {@stats}","@l":"Verbose","stats":{"StartTime":"2021-07-10T16:16:43.8024756+00:00","EndTime":"2021-07-10T16:16:45.8024119+00:00","Duration":"00:00:01.9999363","BytesDownloaded":4930251,"Mbps":18.808014043792216,"$type":"NetworkingStatsEventArgs"},"RoomId":22603245,"SourceContext":"BililiveRecorder.Core.Room","ProcessId":11,"ThreadId":51}

**Comment by valkjsaaa** [comment]
你好像发的 log 都是 _B站录播姬_ 的 log，没有看到对应的 webhook 的 log，要不你把完整的贴一下吧，你可以这么操作：`sudo docker logs auto-bilibili-recorder-new-test > log`。如果你的 config 里有账号，别忘了把前几行登陆的部分删掉。另外，`Dockerfile` 里应该已经设置了时区是 UTC+8，没改动的话你所在的时区不应该影响录播。另外把录播对应的 `all.concat.txt` 和 `.all.video.log` 上传一下吧，这里有具体合并时包含的视频信息，和合并的日志

**Comment by valkjsaaa** [comment]
另外，录播脚本的逻辑是如果直播结束（有可能因为下播，也可能因为断流时间过长）后 1 分钟如果不重新开播，就会试图上传一个无弹幕版录播（如果期间分辨率有改动，则不会上传），如果 5 分钟内不重新开播，就会上传弹幕版录播。期间如果主播重新开播，就会立刻继续录播，并在结束后重试上述操作。

**Comment by Shiori514** [comment]
嗯，我看了一下，是先上传了第一个`.flv`分段，然后用完整的高能弹幕版的`.bar.mp4`去换源了，然后出现了转码的错误

![换源转码错误](https://user-images.githubusercontent.com/52780931/125333999-74819a80-e37d-11eb-9b64-06caec79dd97.jpeg)

<details>
  <summary>涉及文件的目录结构</summary>

**20210710**
![文件夹20210710](https://user-images.githubusercontent.com/52780931/125334286-c9bdac00-e37d-11eb-8dbd-26881ee87a5f.jpeg)
**20210711**
![文件夹20210711](https://user-images.githubusercontent.com/52780931/125334300-ce826000-e37d-11eb-9d7e-1f43e55e2492.jpeg)

</details>

[22603245-20210710-230833-429.all.concat.txt](https://github.com/valkjsaaa/auto-bilibili-recorder/files/6803494/22603245-20210710-230833-429.all.concat.txt)

[22603245-20210710-230833-429.all.video.log](https://github.com/valkjsaaa/auto-bilibili-recorder/files/6803497/22603245-20210710-230833-429.all.video.log)

Docker由于想要先稳定用，删掉改用旧版本了，所以log丢失了……后面我试试能不能复现吧

**Comment by valkjsaaa** [comment]
好像真是夸日直播的问题，我赶紧修复一下，感谢反馈！

**Comment by valkjsaaa** [comment]
fix 啦

**Comment by Shiori514** [comment]
辛苦了！
